@extends('frontend.layouts.app')
@section('title')
    HeshelGhor | Return Policy
@endsection

@section('content')
    <main class="main mt-6">
        <div class="container">
            <p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: center;"><strong><span style='font-size:24px;line-height:107%;font-family:"Times New Roman",serif;'>Return policy</span></strong></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>If there is any problem with the product after receiving the purchased product from the platform of Heshelghor.com, within 12 (twelve) hours you have to complain by registering in the complaint form on the Heshelghor.com website/App. Within a maximum of 7(seven) working days to receive a product change or a full refund, the product must be returned to the head office of Heshelghor.com at your own risk. Change of product or full price will be paid within 10-15 (ten-fifteen) working days if the product is deemed correct by verification and selection.</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>In case of product problems (such as broken, torn, wrong size, product not working, product mismatch with photo, etc.) after receiving the purchased product from the Heshelghor.com platform, you may refund the actual product or refund the full price subject to the following conditions.</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: decimal;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>Within a maximum of 12 (twelve) hours after receiving the delivery of the purchased goods from the platform of Heshelghor.com, you have to complain by registering in the complaint form on the Heshelghor.com website/App. The exact product must match the IMEI / Name / Picture / Brand / Serial Number / Registration Number / MRP Tag / Barcode, etc. and the MRP tag must be intact and clearly visible in the picture.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>Heshelghor.com will notify you of your refund or exchange complaint through verification. If your complaint is deemed correct, you will be given a confirmation code via e-mail / SMS. In order to change using this code In order to change your product or get a full refund, you need to register in the refund form through our website/app and after receiving the confirmation code, the refund form must be registered within 24 hours and the product must be returned to the head office of Heshelghor.com at its own responsibility within a maximum of 7 (seven) working days.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>In the case of Cash on Delivery (COD), delivery charges for products purchased from the Heshelghor.com platform must be paid in advance.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>Heshelghor.com will refund the value of the purchased product within 10-15 (ten-fifteen) working days after verifying and sorting out your returned product and verifying the veracity of your complaint. In the case of Cash on Delivery (COD) the return policy will refund the value of your purchased product within 10-15 (ten-fifteen) working days of your payment (Bkash/Nagad) or through your bank account. The correct product will be delivered to the address given by you within 7 (seven) working days after verification of the authenticity of your complaint after receiving the returned product for your exchange.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>In case of refund, the box of the product or the accessories including the original packaging such as the product manual, warranty card, seal, tag, etc. must be in a completely intact condition.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>Products purchased from the Heshelghor.com platform will not be considered refundable after use.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>Our refunds and replacements do not apply to any offered product purchased from the Heshelghor.com platform.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>If the product has the price written on it and for some reason, the price of Heshelghor.com Merchant is more than that, in that case, the extra price you must register the complaint with the price tag picture through our website/app within 12 (twelve) hours immediately. If your complaint is deemed to be correct, the extra price you paid will be paid within 10-15 (ten-fifteen) working days of the way you paid the price. In the case of Cash on Delivery (COD) the refund policy will be refunded within 10-15 (ten-fifteen) working days of the extra value paid by you (Bkash / Nagad) or paid through your bank account.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>If your purchased product is not in stock of the Merchant, the price of the product will be refunded within 10-15 (ten-fifteen) working days through which you sent the product. If you select Cash on Delivery (COD), refund there is no amount because you did not pay for your order.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>If you do not wish to take the purchased product or change your mind, you must cancel the product within 60 (sixty) minutes through the Heshelghor.com website/app. If the product you have purchased is processed for delivery, you will be reimbursed within 10-15 (ten-fifteen) working days of deducting the delivery charge of the product from the price you paid and the remaining amount will be paid through the same means. In the case of Cash on Delivery (COD), the order will not be considered cancelled if the product purchased by you has been processed for delivery but in the case of delivery of your purchased product, the full value of the product will be paid by 10-15(Ten-fifteen) will be refunded within working days.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>Our complaints team will call you for any complaints regarding products and services purchased from the Heshelghor.com platform. That&apos;s why we want to get you active on the phone until your complaint is resolved. If the number provided in your contact is not active then the alternative number must be active. If we do not receive any of your cooperation within 10 working days by phone or e-mail, we will consider your complaint to be settled.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
    <ol style="margin-bottom:0in;list-style-type: undefined;">
        <li style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif;"><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:16px;'>In case of incorrect delivery (Customer receives the delivery message but the product is not delivered): If the product is not delivered and you have received a delivery confirmation e-mail / SMS, the customer will then have to report the complaint to the Complaint Option using Heshelghor.com website/app to investigate the product, within 2 (two) days from the date of delivery confirmation.</span></li>
    </ol>
</div>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Decision changes for returns and refunds apply to all products purchased from the Heshelghor.com platform:</span></strong></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Clothing, sunglasses, shoes etc.</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Numbers 1, 2, 3, 4, 5, 6 and 7 are mentioned above in case of loss of product purchased from Heshelghor.com platform such as product is broken, torn, the wrong size, product not working, product mismatch with photo etc. The policy must be followed.</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Note that if the product purchased from the Heshelghor.com platform is damaged, defective, incorrect or incomplete or does not match the image, a complaint must be registered through the Heshelghor.com website or apps. Note that items must not be worn or washed or product tags must remain intact. Delivery charges must apply if any used product is rejected and returned to the customer&apos;s address.</span></p>
<p style="margin: 0in 0in 8pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>The change of decision for return and refund does not apply to all products purchased from the Heshelghor.com platform:</span></strong></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Makeup, Fragrances, Moisturizers, Creams, Scrubs, Oils, Bath &amp; Body Accessories, Personal Care, Lingerie &amp; Men&apos;s Lingerie &amp; Health, Sexual, Fitness, Shape Wear, Food, Supplement, Glasses, Jewelry, Watch, All Custom Items, Fine Jewelry, Gold, Diamonds, Gems, Bedding &amp; Bath, Furniture &amp; Lighting, Kitchen &amp; Dining, Home Decor, Home Improvement, Household &amp; Home Storage Supplies, Lawn &amp; Garden, Bags &amp; Luggage, Play Clock, Dancing &amp; Gymnastics, Exercise &amp; Fitness, Sports, Nutrition and Supplement, Outdoor Equipment, Fitness &amp; Other Sports Equipment, Toys &amp; Games, Baby Care &amp; Hygiene, Baby Diapers &amp; Poultry, Bakeries, Beverages, Baking &amp; Cooking, Cigars &amp; Cigarettes, Powdered Milk, Packaged Foods, Party Accessories, Snacks, meat and seafood, fruits, books and stationery, pets, automobiles and motorcycles, machinery, industrial equipment, tools etc.</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Numbers 1, 2, 3, 4, 5, 6 and 7 are mentioned above in case of loss of product purchased from Henschel house platform such as product is broken, torn, the wrong size, product not working, product mismatch with photo etc. The policy must be followed.</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Note: For product-related issues after the use or return policy expires, please check if the product is under seller or brand warranty or guarantee. Contact the seller or manufacturer for a warranty or guarantee on different products. Heshelghor.com does not provide a warranty or guarantee on any type of product.</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>The warranty or guarantee of all products purchased from the Heshelghor.com platform is borne by the seller or manufacturer and change of decision for return/refund is not applicable such as:</span></strong></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Phones, Tabs, Batteries, Chargers, Earphones, Headsets, Mobiles, Laptops, Certified Refurbished Laptops, Components, Processors, Projectors, Storage, Printers, Scanners, Headphones, Speakers, Consoles &amp; PC / Video Games, Gaming Consoles, etc, Television, camera, drone, lens, flash, filter microphone, video glasses, remote controller, musical instruments, audio and entertainment equipment, portable player, microwave, air conditioning, air cooler, fridge, iron machine, washing, sealing Machines, blender machines, water heaters, electric kettles, greasers, etc.</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Heshelghor.com does not accept returns for any used product content. For any of the products mentioned above, you can register a complaint directly through the Heshelghor.com website/app. If the device shuts down when it arrives, that is, does not turn on completely, or if the device is already active, or the brand seal is opened or removed, please contact the seller brand warranty provider directly for manufacturer&apos;s warranty information. Heshelghor.com does not offer warranties or guarantees of any kind.</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 0.0001pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Mobile phones are considered active only after inserting a SIM card in the tab, mobile or once the phone is connected to the internet via WiFi. In this case, there is no chance of a return or refund of Heshelghor.com. Heshelghor.com does not offer warranties or guarantees of any kind.</span></p>
<p style="margin: 0in 0in 8pt 0.5in; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Products that cannot be returned&nbsp;</span></strong><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>for example- all software products that are labelled as non-refundable on their product description page. For any software-related technical issues or installation issues, please contact the brand warranty provider directly for information regarding the manufacturer&apos;s warranty. Heshelghor.com does not offer warranties or guarantees of any kind.</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>Heshelghor.com reserves the right to cancel your order at any time for unavoidable reasons, even after order confirmation from the Heshelghor.com platform. In this case, if the advance price is paid, the price paid by you will be refunded within 10-15 (ten-fifteen) working days through the same medium through which you paid for the purchased product. Again, if you select Cash on Delivery (COD), there is no refund because you did not pay for your order.</span></p>
<p style="margin: 0in 0in 8pt; line-height: 1.5; font-size: 15px; font-family: Calibri, sans-serif; text-align: justify;"><span style='font-size:16px;line-height:107%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
        </div>


    </main>
    <!-- End Main -->
@endsection

@push('styles')
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
@endpush

@push('scripts')
@endpush
